version: '3.3'
networks:
  des-web:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mongodb-storage:

services:
  ing.des.test:
    ports:
      - '8080:80'
    container_name: ing.des.test
    volumes:
      - $PWD/app
    image: ing.des.test
    networks:
      - des-web
    environment:
#      - 'MONGO_USER=user' #optional to use, needs to be setup on MongoDB as well accordingly
#      - 'MONGO_PASS=some-password' #optional to use, needs to be setup on MongoDB as well accordingly
      - 'MONGO_HOST=172.20.0.2'
      - 'MONGO_PORT=27017'
      - 'MONGO_DB_NAME=ing-des'
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      des-web:
        ipv4_address: 172.20.0.2
    volumes:
      - mongodb-storage:/data/db
    expose:
      - '27017'
